// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotivAi.Models;

#nullable disable

namespace MotivAi.Migrations
{
    [DbContext(typeof(MotivAiContext))]
    [Migration("20251027121741_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MotivAi.Models.AI_Request", b =>
                {
                    b.Property<int>("Request_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Request_id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Response_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Request_id");

                    b.HasIndex("User_id");

                    b.ToTable("AI_Requests");
                });

            modelBuilder.Entity("MotivAi.Models.Attachment", b =>
                {
                    b.Property<int>("Attachment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Attachment_id"));

                    b.Property<string>("File_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mime_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<int>("Task_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Uploaded_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Attachment_id");

                    b.HasIndex("Task_id");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("MotivAi.Models.Calendar_Event", b =>
                {
                    b.Property<int>("Event_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Event_id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Event_id");

                    b.HasIndex("User_id");

                    b.ToTable("Calendar_Events");
                });

            modelBuilder.Entity("MotivAi.Models.Goal", b =>
                {
                    b.Property<int>("Goal_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Goal_id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Progress_percentage")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status_id")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Goal_id");

                    b.HasIndex("User_id");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("MotivAi.Models.Habit", b =>
                {
                    b.Property<int>("Habit_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Habit_id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Frequency_id")
                        .HasColumnType("int");

                    b.Property<int>("Frequency_id1")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Habit_id");

                    b.HasIndex("Frequency_id1");

                    b.HasIndex("User_id");

                    b.ToTable("Habits");
                });

            modelBuilder.Entity("MotivAi.Models.Habit_Frequency", b =>
                {
                    b.Property<int>("Frequency_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Frequency_id"));

                    b.Property<string>("Frequency_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Frequency_id");

                    b.ToTable("Habit_Frequencies");
                });

            modelBuilder.Entity("MotivAi.Models.Notification", b =>
                {
                    b.Property<int>("Notification_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Notification_id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.Property<int>("Type_id")
                        .HasColumnType("int");

                    b.Property<int>("Type_id1")
                        .HasColumnType("int");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Notification_id");

                    b.HasIndex("Type_id1");

                    b.HasIndex("User_id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MotivAi.Models.Notification_Type", b =>
                {
                    b.Property<int>("Type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Type_id"));

                    b.Property<string>("Type_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Type_id");

                    b.ToTable("Notification_Types");
                });

            modelBuilder.Entity("MotivAi.Models.Role", b =>
                {
                    b.Property<int>("Role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Role_id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Role_id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MotivAi.Models.Task", b =>
                {
                    b.Property<int>("Task_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Task_id"));

                    b.Property<bool>("Completion_status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Goal_id")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status_id")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Task_id");

                    b.HasIndex("Goal_id");

                    b.HasIndex("Status_id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("MotivAi.Models.Task_Status", b =>
                {
                    b.Property<int>("Status_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Status_id"));

                    b.Property<string>("Status_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Status_id");

                    b.ToTable("Task_Status");
                });

            modelBuilder.Entity("MotivAi.Models.User", b =>
                {
                    b.Property<int>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Is_active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Last_login")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Role_id")
                        .HasColumnType("int");

                    b.HasKey("User_id");

                    b.HasIndex("Role_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MotivAi.Models.AI_Request", b =>
                {
                    b.HasOne("MotivAi.Models.User", "User")
                        .WithMany("AI_Requests")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotivAi.Models.Attachment", b =>
                {
                    b.HasOne("MotivAi.Models.Task", "Task")
                        .WithMany("Attachments")
                        .HasForeignKey("Task_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("MotivAi.Models.Calendar_Event", b =>
                {
                    b.HasOne("MotivAi.Models.User", "User")
                        .WithMany("Calendar_Events")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotivAi.Models.Goal", b =>
                {
                    b.HasOne("MotivAi.Models.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotivAi.Models.Habit", b =>
                {
                    b.HasOne("MotivAi.Models.Habit_Frequency", "Frequency")
                        .WithMany("Habits")
                        .HasForeignKey("Frequency_id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotivAi.Models.User", "User")
                        .WithMany("Habits")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frequency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotivAi.Models.Notification", b =>
                {
                    b.HasOne("MotivAi.Models.Notification_Type", "Type")
                        .WithMany("Notifications")
                        .HasForeignKey("Type_id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotivAi.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotivAi.Models.Task", b =>
                {
                    b.HasOne("MotivAi.Models.Goal", "Goal")
                        .WithMany("Tasks")
                        .HasForeignKey("Goal_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotivAi.Models.Task_Status", "Status")
                        .WithMany("Tasks")
                        .HasForeignKey("Status_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MotivAi.Models.User", b =>
                {
                    b.HasOne("MotivAi.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("Role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MotivAi.Models.Goal", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("MotivAi.Models.Habit_Frequency", b =>
                {
                    b.Navigation("Habits");
                });

            modelBuilder.Entity("MotivAi.Models.Notification_Type", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("MotivAi.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MotivAi.Models.Task", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("MotivAi.Models.Task_Status", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("MotivAi.Models.User", b =>
                {
                    b.Navigation("AI_Requests");

                    b.Navigation("Calendar_Events");

                    b.Navigation("Goals");

                    b.Navigation("Habits");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
